openapi: 3.1.0
info:
  title: Confident AI Metrics API
  version: 1.0.0

servers:
  - x-fern-server-name: Confident AI
    url: https://api.confident-ai.com/

tags:
  - name: Metric Collections
    description: Metric Collection API
    externalDocs:
      description: Learn about metric collection
      url: https://documentation.confident-ai.com/api/metrics/collections

paths:
  /v1/metric-collections:
    post:
      x-fern-server-name: Confident AI
      tags:
        - Metric Collections
      summary: Add Collection
      operationId: createMetricCollection
      requestBody:
        description: Create a metric collection
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMetricCollection'
            examples:
              example1:
                summary: Create a Metric Collection
                value:
                  name: "Collection Name"
                  multiTurn: false
                  metricSettings:
                    - metric: 
                        value: "Answer Relevancy"
                      threshold: 0.8
      responses:
        "200":
          description: Metric Collection successfully added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateMetricResponse"
              examples:
                example1:
                  summary: Create a Metric Collection
                  value:
                    success: true
                    data:
                      id: METRIC-COLLECTION-ID

    get:
      x-fern-server-name: Confident AI
      tags:
        - Metric Collections
      summary: List Metric Collections
      operationId: listMetricCollections
      responses:
        "200":
          description: Metric Collections retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetMetricCollectionResponse"
              examples:
                example1:
                  summary: Get all Metric Collections
                  value:
                    success: true
                    data:
                      metricCollections:
                        - id: "COLLECTION-ID"
                          name: "New Collection Name"
                          multiTurn: false
                          metricSettings:
                            - metric: 
                                name: "Faithfulness"
                              activated: true
                              threshold: 0.5
                              includeReason: true
                              strictMode: false

  /v1/metric-collections/{id}:
    put:
      x-fern-server-name: Confident AI
      tags:
        - Metric Collections
      summary: Update Collection
      operationId: updateMetricCollection
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Update a metric collection
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMetricCollection'
            examples:
              example1:
                summary: Update Metric Collection Example
                value:
                  name: "New Collection Name"
                  multiTurn: false
                  metricSettings:
                    - metric: 
                        name: "Faithfulness"
                      threshold: 0.5
      responses:
        "200":
          description: Metric Collection successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateMetricCollectionResponse"
              examples:
                example1:
                  summary: Update Metric Collection Example
                  value:
                    success: true


components:
  schemas:
    CreateMetricCollection:
      type: object
      description: Request schema to create or update a metric collection
      properties:
        name:
          type: string
          description: Name of the metric collection
        metricSettings:
          type: array
          description: List of metric settings for the collection
          items:
            type: object
            properties:
              metric:
                type: object
                properties:
                  name: 
                    type: string
                  criteria:
                    type: string
                  evaluationSteps:
                    type: string
                  evaluationParams:
                    type: array
                  multiTurn: 
                    type: boolean
                required:
                  - name
              activated:
                type: boolean
              threshold:
                type: number
                description: Threshold value for the metric
              includeReason:
                type: boolean
              strictMode:
                type: boolean
            required:
              - metric
      required:
        - name
        - multiTurn
        - metricSettings

    CreateMetricResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            id:
              type: string
          required:
            - id
      required:
        - success
        - data

    UpdateMetricCollectionResponse:
      type: object
      properties:
        success:
          type: boolean
      required:
        - success

    GetMetricCollectionResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            metricCollections:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  multiTurn:
                    type: boolean
                  metricSettings:
                    type: array
                    items:
                      type: object
                      properties:
                        metric:
                          type: object
                          properties:
                            name:
                              type: string
                            required:
                              - name
                        activated:
                          type: boolean
                        threshold:
                          type: number
                        includeReason:
                          type: boolean
                        strictMode:
                          type: boolean
                      required:
                        - metric
                        - activated
                        - threshold
                        - includeReason
                        - strictMode
                required:
                  - id
                  - name
                  - multiTurn
                  - metricSettings
          required:
            - metricCollections
      required:
        - success
        - data